In [1]:
import pandas as pd
dataset=pd.read_csv("insurance.csv")
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [2]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,True,False,True,False,False
1334,18,31.920,0,2205.98080,False,False,False,False,False
1335,18,36.850,0,1629.83350,False,False,False,True,False
1336,21,25.800,0,2007.94500,False,False,False,False,True
1337,61,29.070,0,29141.36030,False,True,True,False,False

In [3]:
x=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']] 
y=dataset['charges']

In [4]:
x

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [5]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y,test_size=0.2, random_state=42
)

In [10]:
from sklearn.model_selection import GridSearchCV 
from sklearn.tree import DecisionTreeRegressor
param_grid = param_grid = param_grid = {
    'criterion': ['squared_error', 'absolute_error', 'poisson'],
    'max_features': [None, 'sqrt', 'log2'],
    'splitter': ['best', 'random']
}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [13]:
re=grid.cv_results_ 
grid_predictions = grid.predict(x_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'log2', 'splitter': 'best'}: 0.7897313207264873

In [14]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.023604,0.002271,0.012149,0.002035,squared_error,NaN,best,"{'criterion': 'squared_error', 'max_features':...",0.700804,0.813726,0.602869,0.597649,0.716266,0.686263,0.080206,2
1,0.020385,0.001306,0.009920,0.001154,squared_error,NaN,random,"{'criterion': 'squared_error', 'max_features':...",0.710617,0.693338,0.649084,0.627684,0.635645,0.663273,0.032792,10
2,0.016740,0.000811,0.010115,0.000221,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.688788,0.766337,0.563800,0.661178,0.660941,0.668209,0.064894,8
3,0.018191,0.001003,0.011243,0.000807,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.686241,0.745212,0.621767,0.380849,0.724753,0.631764,0.132321,16
4,0.017985,0.000622,0.010064,0.000560,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.691083,0.809441,0.672790,0.643217,0.644505,0.692207,0.061315,1
5,0.015110,0.000641,0.011498,0.001693,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.703438,0.768386,0.593150,0.621931,0.608164,0.659014,0.066685,13
6,0.061768,0.009309,0.014948,0.002577,absolute_error,NaN,best,"{'criterion': 'absolute_error', 'max_features'...",0.725275,0.739017,0.654231,0.617685,0.611761,0.669594,0.053283,7
7,0.070755,0.008475,0.020568,0.001794,absolute_error,NaN,random,"{'criterion': 'absolute_error', 'max_features'...",0.690170,0.815702,0.544179,0.615337,0.695542,0.672186,0.090646,5
8,0.051856,0.005002,0.018929,0.001353,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.704509,0.726476,0.559208,0.635081,0.686307,0.662316,0.059742,11
9,0.055257,0.003700,0.019123,0.002219,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.711416,0.659565,0.623599,0.636356,0.724485,0.671084,0.040179,6
10,0.056436,0.003499,0.017756,0.002019,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.696957,0.678295,0.657894,0.476131,0.622606,0.626377,0.079068,17
11,0.056033,0.002176,0.017888,0.003185,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.732616,0.742770,0.568309,0.607888,0.718070,0.673931,0.071622,3
12,0.037283,0.003393,0.017523,0.001721,poisson,NaN,best,"{'criterion': 'poisson', 'max_features': None,...",0.734021,0.734483,0.551123,0.595629,0.682312,0.659514,0.074191,12
13,0.031558,0.002234,0.018236,0.002905,poisson,NaN,random,"{'criterion': 'poisson', 'max_features': None,...",0.701580,0.726593,0.583623,0.594221,0.711484,0.663500,0.061503,9
14,0.035118,0.003842,0.017850,0.002751,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.599252,0.713239,0.661521,0.625819,0.658689,0.651704,0.038348,15
15,0.020553,0.003670,0.010107,0.000730,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.641003,0.709085,0.540310,0.669565,0.702733,0.652539,0.061213,14
16,0.019921,0.001415,0.010358,0.000984,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.672640,0.764774,0.624499,0.683637,0.621508,0.673411,0.052036,4
17,0.017045,0.001468,0.009423,0.000666,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.448446,0.647790,0.544542,0.462415,0.645215,0.549682,0.085606,18