In [2]:
import pandas as pd
dataset=pd.read_csv("insurance.csv")
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,True,False,True,False,False
1334,18,31.920,0,2205.98080,False,False,False,False,False
1335,18,36.850,0,1629.83350,False,False,False,True,False
1336,21,25.800,0,2007.94500,False,False,False,False,True
1337,61,29.070,0,29141.36030,False,True,True,False,False

In [4]:
x=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']] 
y=dataset['charges']

In [5]:
x

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [6]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y,test_size=0.2, random_state=42
)

In [8]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [9]:
from sklearn.model_selection import GridSearchCV 
from sklearn.svm import SVR 
param_grid = {'kernel':['rbf','poly','sigmoid','linear'], 'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [10]:
re=grid.cv_results_
print("TheR_scorevalueforbestparameter{}:".format(grid.best_params_))

TheR_scorevalueforbestparameter{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}:

In [11]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.376581,0.132284,0.309965,0.023764,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.062989,-0.117796,-0.019407,-0.051523,-0.004844,-0.051312,0.039329,35
1,1.206248,0.096617,0.107718,0.008240,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.003108,-0.044957,0.049030,0.006338,0.058407,0.014385,0.037018,32
2,1.066475,0.308442,0.170983,0.009056,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.004101,-0.047801,0.047355,-0.001120,0.058911,0.010649,0.038598,34
3,0.566127,0.047662,0.098743,0.008173,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.384077,0.407059,0.446891,0.361929,0.438467,0.407684,0.032050,25
4,0.758523,0.024043,0.290120,0.011755,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.063017,-0.117866,-0.019357,-0.051452,-0.004894,-0.051317,0.039350,36
5,0.513406,0.009737,0.099058,0.003918,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.003679,-0.043919,0.048226,0.004902,0.059242,0.014426,0.036773,31
6,0.778353,0.012562,0.152863,0.011500,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.003979,-0.047583,0.047179,-0.001392,0.059107,0.010667,0.038555,33
7,0.546574,0.033575,0.092441,0.005935,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.384077,0.407059,0.446891,0.361929,0.438467,0.407684,0.032050,25
8,0.742026,0.020238,0.284643,0.016011,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.254591,0.241941,0.307474,0.270513,0.312735,0.277451,0.028206,29
9,0.555699,0.031312,0.102860,0.009954,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.535869,0.566195,0.576287,0.505947,0.579890,0.552837,0.028095,22
10,0.788476,0.012458,0.159382,0.013828,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.452802,0.513735,0.503132,0.427898,0.500963,0.479706,0.033366,24
11,0.605430,0.015766,0.093145,0.012471,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.565010,0.641031,0.614605,0.563819,0.609558,0.598805,0.030048,19
12,0.767228,0.013912,0.290824,0.006921,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.254350,0.241451,0.307766,0.271076,0.312421,0.277413,0.028327,30
13,0.565503,0.026184,0.096514,0.004456,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.536963,0.568599,0.574402,0.503554,0.581853,0.553074,0.029106,21
14,0.766254,0.022074,0.159690,0.007423,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.452407,0.514772,0.504560,0.427438,0.501650,0.480165,0.034074,23
15,0.604545,0.019288,0.089307,0.011021,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.565010,0.641031,0.614605,0.563819,0.609558,0.598805,0.030048,19
16,0.874321,0.022504,0.287551,0.006644,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.758010,0.830323,0.750117,0.716685,0.764508,0.763929,0.037057,11
17,0.873937,0.194832,0.103516,0.004445,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.796594,0.875412,0.788212,0.734027,0.830765,0.805002,0.046929,10
18,0.870980,0.032331,0.157676,0.003882,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.230793,0.346088,0.314499,0.257601,0.394088,0.308614,0.058997,27
19,0.810429,0.115602,0.094654,0.004950,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.692098,0.721724,0.650031,0.521086,0.719723,0.660932,0.074564,13
20,0.872774,0.006967,0.259273,0.017448,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.757901,0.830113,0.750240,0.716876,0.764297,0.763885,0.036927,12
21,0.844957,0.252457,0.099442,0.008035,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.796804,0.875664,0.787910,0.733964,0.831153,0.805099,0.047080,9
22,0.838230,0.044691,0.152288,0.003644,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.268397,0.303674,0.318148,0.262902,0.358092,0.302243,0.034835,28
23,0.820406,0.102121,0.095684,0.002255,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.692098,0.721724,0.650031,0.521086,0.719723,0.660932,0.074564,13
24,0.913913,0.035830,0.300877,0.034234,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.803757,0.884793,0.779325,0.752033,0.833867,0.810755,0.045828,7
25,1.275995,0.323765,0.119240,0.016086,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.805475,0.883107,0.792293,0.739360,0.841998,0.812447,0.048296,6
26,0.868728,0.034430,0.158239,0.020934,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.592665,-0.725980,-1.001395,-0.628122,-0.313148,-0.652262,0.222018,38
27,0.989754,0.062973,0.100412,0.006071,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.667154,0.719068,0.649166,0.515902,0.718070,0.653872,0.074305,15
28,1.070702,0.152914,0.356925,0.065399,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.803716,0.884752,0.779370,0.752058,0.833807,0.810741,0.045797,8
29,1.403321,0.165653,0.128797,0.017406,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.805559,0.883063,0.792359,0.739398,0.842033,0.812482,0.048268,4
30,1.202270,0.084308,0.227481,0.056207,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.852224,-0.544869,-0.921709,-0.302713,-0.178029,-0.559909,0.292764,37
31,1.467927,0.065034,0.134440,0.029448,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.667154,0.719068,0.649166,0.515902,0.718070,0.653872,0.074305,15
32,1.450237,0.053079,0.403314,0.026490,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.812728,0.892785,0.788822,0.759567,0.847117,0.820204,0.046282,1
33,2.493750,0.547277,0.121172,0.023358,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.806129,0.883163,0.791702,0.738082,0.843265,0.812468,0.048889,5
34,1.214780,0.053852,0.221039,0.042270,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-2.446592,-2.345682,-2.995007,-2.113382,-1.647155,-2.309563,0.439815,40
35,1.288799,0.104666,0.113046,0.025088,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.666427,0.717132,0.648148,0.515428,0.715564,0.652540,0.073697,17
36,1.030168,0.057903,0.288382,0.010187,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.812695,0.892795,0.788843,0.759559,0.847082,0.820195,0.046281,2
37,1.591446,0.208211,0.093434,0.004730,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.806135,0.883222,0.791709,0.738111,0.843591,0.812554,0.048938,3
38,0.890891,0.039429,0.150943,0.006838,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-2.501481,-2.428676,-2.961004,-1.497841,-1.612036,-2.200208,0.558756,39
39,0.962396,0.074852,0.078131,0.012967,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.666427,0.717132,0.648148,0.515428,0.715564,0.652540,0.073697,17